# Generated by Django 5.0.6 on 2024-07-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0002_article_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
